# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 15e83c8
_src_path: https://github.com/slaclab/eed-java-backend-template.git
github_owner: eed-web-application
project_name: core-work-management
project_slug: core_work_management
