logging:
  level:
    edu.stanford.slac.code_inventory_system: ${CIS_LOG_LEVEL:DEBUG}

server:
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  application:
    name: 'CWM'
  cache:
    type: hazelcast
  ldap:
    urls: ${CIS_LDAP_URI:ldap://localhost:8389}
    base: ${CIS_LDAP_BASE:dc=sdf,dc=slac,dc=stanford,dc=edu}
  data:
    mongodb:
      uri: ${CIS_MONGODB_URI:mongodb://cis:cis@localhost:27017/cis?authSource=cis}
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1MB
      max-file-size: ${CIS_MAX_POST_SIZE:100MB}
      max-request-size: ${CIS_MAX_POST_SIZE:100MB}

edu:
  stanford:
    slac:
      ad:
        eed:
          baselib:
            app-token-prefix: ${spring.application.name}
            app-token-jwt-key: ${CIS_APP_TOKEN_JWT:token-header-key}
            user-header-name: ${CIS_AUTH_HEADER:x-vouch-idp-accesstoken}
            oauth-server-discover: ${CIS_OIDC_CONFIGURATION_ENDPOINT:https://dex.slac.stanford.edu/.well-known/openid-configuration}
            root-user-list: ${CIS_ROOT_USERS}
            root-authentication-token-list-json: ${CIS_ROOT_AUTHENTICATION_TOKEN_JSON:[]}
          mongodb:
            db_admin_uri: ${CIS_ADMIN_MONGODB_URI:mongodb://admin:admin@localhost:27017/?authSource=admin}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}

# swagger-ui custom path
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    path: /api-docs

mongock:
  migration-scan-package:
    - edu.stanford.slac.code_inventory_system.migration
  throw-exception-if-cannot-obtain-lock: true #Default true
  track-ignored: false #Default true
  transaction-enabled: false
  runner-type: initializingbean
  enabled: true #Default true